# -*- coding: utf-8 -*-
"""test_sampling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7ndEqlzi7hx64AvkBPl1Dc_of9mxpUL
"""

import numpy as np
import pandas as pd
import pytest

from src.data.sampling import sample_patches_by_patient


def make_metadata(
    patients: dict[int, int],
) -> pd.DataFrame:
    """Create synthetic patch metadata for testing."""
    rows = []

    for patient, n_patches in patients.items():
        for patch_id in range(n_patches):
            rows.append(
                {
                    "patient": patient,
                    "patch_id": f"{patient}_{patch_id}",
                }
            )

    return pd.DataFrame(rows)


def test_samples_exact_number_per_patient() -> None:
    """Each patient should contribute exactly n_samples patches."""
    metadata = make_metadata(
        {
            1: 10,
            2: 20,
            3: 30,
        }
    )

    sampled = sample_patches_by_patient(
        metadata,
        n_samples=5,
        seed=42,
    )

    counts = sampled["patient"].value_counts().sort_index()

    expected = pd.Series(
        {
            1: 5,
            2: 5,
            3: 5,
        },
        name="patient",
    )

    pd.testing.assert_series_equal(
        counts,
        expected,
    )


def test_sampling_is_without_replacement() -> None:
    """A patient should not contain duplicate sampled patches."""
    metadata = make_metadata(
        {
            1: 20,
            2: 20,
        }
    )

    sampled = sample_patches_by_patient(
        metadata,
        n_samples=10,
        seed=42,
    )

    assert not sampled["patch_id"].duplicated().any()


def test_sampling_is_reproducible() -> None:
    """The same seed should produce the same sampled patches."""
    metadata = make_metadata(
        {
            1: 20,
            2: 20,
            3: 20,
        }
    )

    sampled_a = sample_patches_by_patient(
        metadata,
        n_samples=10,
        seed=42,
    )

    sampled_b = sample_patches_by_patient(
        metadata,
        n_samples=10,
        seed=42,
    )

    pd.testing.assert_frame_equal(
        sampled_a,
        sampled_b,
    )


def test_different_seeds_can_produce_different_samples() -> None:
    """Different seeds should not be forced to produce identical samples."""
    metadata = make_metadata(
        {
            1: 50,
            2: 50,
        }
    )

    sampled_a = sample_patches_by_patient(
        metadata,
        n_samples=20,
        seed=42,
    )

    sampled_b = sample_patches_by_patient(
        metadata,
        n_samples=20,
        seed=123,
    )

    assert not sampled_a["patch_id"].equals(
        sampled_b["patch_id"]
    )


def test_sampling_preserves_patient_identity() -> None:
    """Every sampled row must belong to an existing patient."""
    metadata = make_metadata(
        {
            1: 10,
            2: 10,
            3: 10,
        }
    )

    sampled = sample_patches_by_patient(
        metadata,
        n_samples=5,
        seed=42,
    )

    assert set(sampled["patient"]) == {1, 2, 3}


def test_sampling_without_replacement() -> None:
    """The number of unique sampled rows should equal total sampled rows."""
    metadata = make_metadata(
        {
            1: 15,
            2: 15,
        }
    )

    sampled = sample_patches_by_patient(
        metadata,
        n_samples=10,
        seed=42,
    )

    assert len(sampled) == 20
    assert len(sampled.index.unique()) == 20


def test_raises_when_patient_has_too_few_patches() -> None:
    """Sampling should fail if a patient has insufficient patches."""
    metadata = make_metadata(
        {
            1: 10,
            2: 3,
        }
    )

    with pytest.raises(ValueError, match="fewer than"):
        sample_patches_by_patient(
            metadata,
            n_samples=5,
            seed=42,
        )


def test_raises_for_invalid_n_samples() -> None:
    """n_samples must be positive."""
    metadata = make_metadata(
        {
            1: 10,
            2: 10,
        }
    )

    with pytest.raises(ValueError, match="positive"):
        sample_patches_by_patient(
            metadata,
            n_samples=0,
            seed=42,
        )


def test_raises_for_missing_patient_column() -> None:
    """A missing patient column should produce a clear error."""
    metadata = pd.DataFrame(
        {
            "patch_id": [1, 2, 3],
        }
    )

    with pytest.raises(KeyError, match="Patient column"):
        sample_patches_by_patient(
            metadata,
            n_samples=2,
            seed=42,
        )


def test_seed_must_be_integer() -> None:
    """The random seed should be explicitly integer-valued."""
    metadata = make_metadata(
        {
            1: 10,
            2: 10,
        }
    )

    with pytest.raises(TypeError, match="integer"):
        sample_patches_by_patient(
            metadata,
            n_samples=5,
            seed=3.14,
        )

