# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Is6szAFUqMWeka8DvzuJNuzk3qv0mED
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import pandas as pd


REQUIRED_COLUMNS = {
    "patient",
    "node",
    "x_coord",
    "y_coord",
    "tumor",
    "slide",
    "center",
    "split",
}


def load_metadata(metadata_path: str | Path) -> pd.DataFrame:
    """Load CAMELYON17 metadata and validate required columns."""
    metadata_path = Path(metadata_path)

    if not metadata_path.exists():
        raise FileNotFoundError(f"Metadata file not found: {metadata_path}")

    metadata = pd.read_csv(metadata_path)

    missing_columns = REQUIRED_COLUMNS - set(metadata.columns)
    if missing_columns:
        raise ValueError(
            f"Metadata is missing required columns: "
            f"{sorted(missing_columns)}"
        )

    return metadata


def summarize_dataset(metadata: pd.DataFrame) -> dict[str, int]:
    """Return basic dataset-level statistics."""
    return {
        "num_samples": len(metadata),
        "num_patients": metadata["patient"].nunique(),
        "num_slides": metadata["slide"].nunique(),
        "num_centers": metadata["center"].nunique(),
    }


def summarize_splits(metadata: pd.DataFrame) -> pd.DataFrame:
    """Return sample counts and proportions for each raw WILDS split."""
    summary = (
        metadata["split"]
        .value_counts()
        .rename_axis("split")
        .reset_index(name="num_samples")
    )

    summary["proportion"] = (
        summary["num_samples"] / len(metadata)
    )

    return summary.sort_values("split").reset_index(drop=True)


def summarize_centers(metadata: pd.DataFrame) -> pd.DataFrame:
    """Return sample counts and proportions for each center."""
    summary = (
        metadata["center"]
        .value_counts()
        .rename_axis("center")
        .reset_index(name="num_samples")
    )

    summary["proportion"] = (
        summary["num_samples"] / len(metadata)
    )

    return summary.sort_values("center").reset_index(drop=True)


def summarize_labels(metadata: pd.DataFrame) -> pd.DataFrame:
    """Return tumor-label counts and proportions."""
    summary = (
        metadata["tumor"]
        .value_counts()
        .rename_axis("tumor")
        .reset_index(name="num_samples")
    )

    summary["proportion"] = (
        summary["num_samples"] / len(metadata)
    )

    return summary.sort_values("tumor").reset_index(drop=True)


def center_label_distribution(metadata: pd.DataFrame) -> pd.DataFrame:
    """
    Compute tumor-label distribution within each center.

    The returned table contains:
        - center
        - tumor
        - num_samples
        - proportion_within_center
    """
    counts = (
        metadata.groupby(["center", "tumor"])
        .size()
        .reset_index(name="num_samples")
    )

    counts["proportion_within_center"] = (
        counts["num_samples"]
        / counts.groupby("center")["num_samples"].transform("sum")
    )

    return counts.sort_values(["center", "tumor"]).reset_index(drop=True)


def tumor_probability_by_center(metadata: pd.DataFrame) -> pd.DataFrame:
    """
    Compute P(Y=1 | center) for every center.

    This measures the empirical association between center and tumor
    label without assuming that such an association exists.
    """
    result = (
        metadata.groupby("center")["tumor"]
        .mean()
        .rename("p_tumor_1")
        .reset_index()
    )

    return result.sort_values("center").reset_index(drop=True)


def patient_structure(metadata: pd.DataFrame) -> pd.DataFrame:
    """Summarize patients by center and number of slides/samples."""
    result = (
        metadata.groupby(["center", "patient"])
        .agg(
            num_samples=("patient", "size"),
            num_slides=("slide", "nunique"),
        )
        .reset_index()
    )

    return result


def slide_structure(metadata: pd.DataFrame) -> pd.DataFrame:
    """Summarize slides by center, patient, and number of samples."""
    result = (
        metadata.groupby(["center", "patient", "slide"])
        .agg(
            num_samples=("slide", "size"),
            num_patients=("patient", "nunique"),
        )
        .reset_index()
    )

    return result


def check_metadata_consistency(metadata: pd.DataFrame) -> dict[str, object]:
    """
    Check basic metadata validity.

    Returns a dictionary of detected problems rather than raising
    exceptions, so the notebook can report them cleanly.
    """
    problems: dict[str, object] = {}

    invalid_tumor = sorted(
        set(metadata["tumor"].dropna().unique()) - {0, 1}
    )
    if invalid_tumor:
        problems["invalid_tumor_values"] = invalid_tumor

    if metadata["patient"].isna().any():
        problems["missing_patient"] = int(
            metadata["patient"].isna().sum()
        )

    if metadata["slide"].isna().any():
        problems["missing_slide"] = int(
            metadata["slide"].isna().sum()
        )

    if metadata["center"].isna().any():
        problems["missing_center"] = int(
            metadata["center"].isna().sum()
        )

    if metadata["tumor"].isna().any():
        problems["missing_tumor"] = int(
            metadata["tumor"].isna().sum()
        )

    if metadata["split"].isna().any():
        problems["missing_split"] = int(
            metadata["split"].isna().sum()
        )

    return problems


def find_duplicate_rows(
    metadata: pd.DataFrame,
    subset: Iterable[str] | None = None,
) -> pd.DataFrame:
    """
    Find duplicate metadata rows.

    If subset is provided, duplicates are determined using those columns.
    """
    if subset is None:
        subset = list(metadata.columns)

    subset = list(subset)

    duplicates = metadata[
        metadata.duplicated(subset=subset, keep=False)
    ].copy()

    return duplicates


def find_patient_split_leakage(
    metadata: pd.DataFrame,
) -> pd.DataFrame:
    """
    Find patients appearing in more than one raw split.
    """
    patient_splits = (
        metadata.groupby("patient")["split"]
        .nunique()
        .reset_index(name="num_splits")
    )

    leaking_patients = patient_splits[
        patient_splits["num_splits"] > 1
    ]["patient"]

    return metadata[
        metadata["patient"].isin(leaking_patients)
    ].sort_values(["patient", "split"])


def find_slide_split_leakage(
    metadata: pd.DataFrame,
) -> pd.DataFrame:
    """
    Find slides appearing in more than one raw split.
    """
    slide_splits = (
        metadata.groupby("slide")["split"]
        .nunique()
        .reset_index(name="num_splits")
    )

    leaking_slides = slide_splits[
        slide_splits["num_splits"] > 1
    ]["slide"]

    return metadata[
        metadata["slide"].isin(leaking_slides)
    ].sort_values(["slide", "split"])


def summarize_patient_center_relationship(
    metadata: pd.DataFrame,
) -> pd.DataFrame:
    """
    Check whether patients are associated with multiple centers.
    """
    result = (
        metadata.groupby("patient")["center"]
        .nunique()
        .rename("num_centers")
        .reset_index()
    )

    return result


def summarize_slide_center_relationship(
    metadata: pd.DataFrame,
) -> pd.DataFrame:
    """
    Check whether slides are associated with multiple centers.
    """
    result = (
        metadata.groupby("slide")["center"]
        .nunique()
        .rename("num_centers")
        .reset_index()
    )

    return result

