# -*- coding: utf-8 -*-
"""sampling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7ndEqlzi7hx64AvkBPl1Dc_of9mxpUL
"""

from __future__ import annotations

import numpy as np
import pandas as pd


def sample_patches_by_patient(
    metadata: pd.DataFrame,
    n_samples: int,
    seed: int,
    patient_col: str = "patient",
) -> pd.DataFrame:
    """
    Sample a fixed number of patches from each patient.

    Sampling is performed without replacement and is deterministic for a
    fixed random seed.

    Parameters
    ----------
    metadata:
        DataFrame containing one row per image patch.
    n_samples:
        Number of patches to sample from each patient.
    seed:
        Random seed used for reproducible sampling.
    patient_col:
        Column identifying the patient.

    Returns
    -------
    pd.DataFrame
        DataFrame containing exactly ``n_samples`` rows per patient.

    Raises
    ------
    ValueError
        If n_samples is not positive or if any patient has fewer than
        n_samples available patches.
    KeyError
        If patient_col is not present in metadata.
    """
    if patient_col not in metadata.columns:
        raise KeyError(
            f"Patient column '{patient_col}' not found in metadata."
        )

    if n_samples <= 0:
        raise ValueError("n_samples must be a positive integer.")

    if not isinstance(seed, (int, np.integer)):
        raise TypeError("seed must be an integer.")

    patient_counts = metadata[patient_col].value_counts()

    insufficient_patients = patient_counts[
        patient_counts < n_samples
    ]

    if not insufficient_patients.empty:
        details = insufficient_patients.to_dict()
        raise ValueError(
            "Some patients have fewer than "
            f"{n_samples} available patches: {details}"
        )

    rng = np.random.default_rng(seed)

    sampled_indices: list = []

    for patient in metadata[patient_col].drop_duplicates():
        patient_indices = metadata.index[
            metadata[patient_col] == patient
        ].to_numpy()

        selected_indices = rng.choice(
            patient_indices,
            size=n_samples,
            replace=False,
        )

        sampled_indices.extend(selected_indices.tolist())

    return metadata.loc[sampled_indices].copy()

